version: 2
jobs:
  build:
    docker:
      - image: circleci/python

    steps:
      - run:
          name: Installing GCC, CMake, Ninja, Protobuf
          command: sudo apt-get update && sudo apt-get install -y gcc g++ cmake ninja-build protobuf-compiler
      # Use cached mlir installation if possible.
      - restore_cache:
          key: V2-LLVM-PROJECT-{{ arch }}
      - run:
          name: Install MLIR
          command: |
            # Check whether cache restoration succeeds by checking whether
            # mlir-opt executable exists.
            if [ ! -f llvm-project/build/bin/mlir-opt ]; then
              export MAKEFLAGS=-j4
              source utils/install-mlir.sh
            fi
      - save_cache:
          key: V2-LLVM-PROJECT-{{ arch }}
          paths:
            - llvm-project
      - checkout:
          path: ONNF
      - run:
          name: Pull Submodules
          command: |
            cd ONNF
            git submodule update --init --recursive
      - run:
          name: Install ONNF
          command: source ONNF/utils/install-onnf.sh
      - run:
          name: Run DocCheck
          command: cd ONNF/build && cmake --build . --target check-doc
      - run:
          name: Print the Current Time
          command: date
